export const MUTATIONS = {
  SET_FULLNAME: 'SET_FULLNAME',
  SET_NICKNAME: 'SET_NICKNAME',
  SET_GENDER: 'SET_GENDER',
  SET_BIRTHDATE: 'SET_BIRTHDATE',
  SET_PHONENUMBER: 'SET_PHONENUMBER',
  SET_EMERGENCYPHONENUM: 'SET_EMERGENCYPHONENUM',
  SET_RELATION: 'SET_RELATION',
  SET_IDLINE: 'SET_IDLINE',
  SET_EMAIL: 'SET_EMAIL',
  SET_STUDENTID: 'SET_STUDENTID',
  SET_DEPARTMENT: 'SET_DEPARTMENT',
  SET_PKTB: 'SET_PKTB',
};
