export const departments = [
  { id: 1, name: 'TPB FITB-G' },
  { id: 6, name: 'TPB FITB-C' },
  { id: 8, name: 'TPB FMIPA' },
  { id: 14, name: 'TPB FSRD-G' },
  { id: 20, name: 'TPB FSRD-C' },
  { id: 22, name: 'TPB FTI-G' },
  { id: 27, name: 'TPB FTI-J' },
  { id: 30, name: 'TPB FTI-C' },
  { id: 32, name: 'TPB FTMD' },
  { id: 36, name: 'TPB FTTM-G' },
  { id: 41, name: 'TPB FTTM-C' },
  { id: 45, name: 'TPB FTSL-G' },
  { id: 49, name: 'TPB FTSL-J' },
  { id: 52, name: 'TPB SAPPK-G' },
  { id: 55, name: 'TPB SAPPK-C' },
  { id: 57, name: 'TPB SBM' },
  { id: 60, name: 'TPB SF' },
  { id: 63, name: 'TPB SITH-S' },
  { id: 66, name: 'TPB SITH-R' },
  { id: 71, name: 'TPB STEI' },
];
